TinyWindow: windowManager::TinyWindow_PrintErrorMessage
AddWindow
DisableWindowDecoratorByIndex
DisableWindowDecoratorByName
DoesExistByIndex
DoesExistByName
EnableWindowDecoratorsByIndex
EnableWindowDecoratorsByName
errorCategory
FocusWindowByIndex
FocusWindowByName
GetInstance
GetMousePositionInScreen
GetMousePositionInScreen
GetMousePositionInWindowByIndex
GetMousePositionInWindowByIndex
GetMousePositionInWindowByName
GetMousePositionInWindowByName
GetNumWindows
GetScreenResolution
GetScreenResolution
GetWindowByIndex
GetWindowByName
GetWindowIndexByName
GetWindowIsFullScreenByIndex
GetWindowIsFullScreenByName
GetWindowIsInFocusByIndex
GetWindowIsInFocusByName
GetWindowIsMaximizedByIndex
GetWindowIsMaximizedByName
GetWindowIsMinimizedByIndex
GetWindowIsMinimizedByName
GetWindowNameByIndex
GetWindowPositionByIndex
GetWindowPositionByIndex
GetWindowPositionByName
GetWindowPositionByName
GetWindowResolutionByIndex
GetWindowResolutionByIndex
GetWindowResolutionByName
GetWindowResolutionByName
GetWindowShouldCloseByIndex
GetWindowShouldCloseByName
Initialize
instance
isInitialized
IsInitialized
IsValid
MakeWindowCurrentContextByIndex
MakeWindowCurrentContextByName
MaximizeWindowByIndex
MaximizeWindowByName
MinimizeWindowByIndex
MinimizeWindowByName
nullWindow
Platform_DisableWindowDecorators
Platform_EnableWindowDecorators
Platform_FocusWindow
Platform_InitializeGL
Platform_InitializeWindow
Platform_MakeCurrentContext
Platform_MaximizeWindow
Platform_MinimizeWindow
Platform_RestoreWindow
Platform_SetFullScreen
Platform_SetMousePositionInWindow
Platform_SetWindowPosition
Platform_SetWindowResolution
Platform_SetWindowStyle
Platform_SetWindowTitleBar
Platform_SwapBuffers
PollForEvents
RemoveWindowByIndex
RemoveWindowByName
RestoreWindowByIndex
RestoreWindowByName
screenMousePosition
screenResolution
SetFullScreenByIndex
SetFullScreenByName
SetMousePositionInScreen
SetMousePositionInScreen
SetMousePositionInWindowByIndex
SetMousePositionInWindowByIndex
SetMousePositionInWindowByName
SetMousePositionInWindowByName
SetWindowIconByIndex
SetWindowIconByName
SetWindowOnDestroyedByIndex
SetWindowOnDestroyedByName
SetWindowOnFocusByIndex
SetWindowOnFocusByName
SetWindowOnKeyEventByIndex
SetWindowOnKeyEventByName
SetWindowOnMaximizedByIndex
SetWindowOnMaximizedByName
SetWindowOnMinimizedByIndex
SetWindowOnMinimizedByName
SetWindowOnMouseButtonEventByIndex
SetWindowOnMouseButtonEventByName
SetWindowOnMouseMoveByIndex
SetWindowOnMouseMoveByName
SetWindowOnMouseWheelEventByIndex
SetWindowOnMouseWheelEventByName
SetWindowOnMovedByIndex
SetWindowOnMovedByName
SetWindowOnResizeByIndex
SetWindowOnResizeByName
SetWindowPositionByIndex
SetWindowPositionByIndex
SetWindowPositionByName
SetWindowPositionByName
SetWindowResolutionByIndex
SetWindowResolutionByIndex
SetWindowResolutionByName
SetWindowResolutionByName
SetWindowStyleByIndex
SetWindowStyleByName
SetWindowTitleBarByIndex
SetWindowTitleBarByName
ShutDown
ShutdownWindow
TinyWindow_PrintErrorMessage
tinyWindowError_t
WaitForEvents
WindowExists
WindowGetKeyByIndex
WindowGetKeyByName
windowList
windowManager
WindowSwapBuffersByIndex
WindowSwapBuffersByName
~windowManager
static void windowManager::TinyWindow_PrintErrorMessage (std::error_code e) inline static private
Definition at line 2590 of file TinyWindow.h.
Referenced by AddWindow(), DisableWindowDecoratorByIndex(), DisableWindowDecoratorByName(), DoesExistByIndex(), DoesExistByName(), EnableWindowDecoratorsByIndex(), EnableWindowDecoratorsByName(), FocusWindowByIndex(), FocusWindowByName(), GetMousePositionInScreen(), GetMousePositionInWindowByIndex(), GetMousePositionInWindowByName(), GetNumWindows(), GetScreenResolution(), GetWindowIndexByName(), GetWindowIsFullScreenByIndex(), GetWindowIsFullScreenByName(), GetWindowIsInFocusByIndex(), GetWindowIsInFocusByName(), GetWindowIsMaximizedByIndex(), GetWindowIsMaximizedByName(), GetWindowIsMinimizedByIndex(), GetWindowIsMinimizedByName(), GetWindowNameByIndex(), GetWindowPositionByIndex(), GetWindowPositionByName(), GetWindowResolutionByIndex(), GetWindowResolutionByName(), GetWindowShouldCloseByIndex(), GetWindowShouldCloseByName(), Initialize(), MakeWindowCurrentContextByIndex(), MakeWindowCurrentContextByName(), MaximizeWindowByIndex(), MaximizeWindowByName(), MinimizeWindowByIndex(), MinimizeWindowByName(), Platform_InitializeGL(), Platform_SetWindowStyle(), PollForEvents(), RemoveWindowByIndex(), RemoveWindowByName(), RestoreWindowByIndex(), RestoreWindowByName(), SetFullScreenByIndex(), SetFullScreenByName(), SetMousePositionInScreen(), SetMousePositionInWindowByIndex(), SetMousePositionInWindowByName(), SetWindowIconByIndex(), SetWindowIconByName(), SetWindowOnDestroyedByIndex(), SetWindowOnDestroyedByName(), SetWindowOnFocusByIndex(), SetWindowOnFocusByName(), SetWindowOnKeyEventByIndex(), SetWindowOnKeyEventByName(), SetWindowOnMaximizedByIndex(), SetWindowOnMaximizedByName(), SetWindowOnMinimizedByIndex(), SetWindowOnMinimizedByName(), SetWindowOnMouseButtonEventByIndex(), SetWindowOnMouseButtonEventByName(), SetWindowOnMouseMoveByIndex(), SetWindowOnMouseMoveByName(), SetWindowOnMouseWheelEventByIndex(), SetWindowOnMouseWheelEventByName(), SetWindowOnMovedByIndex(), SetWindowOnMovedByName(), SetWindowOnResizeByIndex(), SetWindowOnResizeByName(), SetWindowPositionByIndex(), SetWindowPositionByName(), SetWindowResolutionByIndex(), SetWindowResolutionByName(), SetWindowStyleByIndex(), SetWindowStyleByName(), SetWindowTitleBarByIndex(), SetWindowTitleBarByName(), ShutDown(), WaitForEvents(), WindowGetKeyByIndex(), WindowGetKeyByName(), WindowSwapBuffersByIndex(), and WindowSwapBuffersByName().
     {
         printf("%s", e.message().c_str());
     }